### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by technout** [scramlo/Better-DDG-Image-Search#1]
Hi, nice DDG addon I was looking for!

But I noticed that the image aspect ratio is not maintained. Images are stretched out.
Is this fixable in an update?

**Comment by scramlo** [comment]
Yeah, I'm sure I can do that. I stopped using FireFox and started using Brave so I haven't used it in a while :) But, I'll try to make a patch.

**Comment by scramlo** [comment]
@technout I just pushed up a patch and after Mozilla reviews it, it will go live. Look for version  1.1.2. I am going to work next on making this a cross-browser extension. Thanks for opening the issue. Blessings!

**Comment by technout** [comment]
Thank you for the quick update! It works like a charm now :)
